//
//  Extensions.swift
//  CalculatorZ
//
//  Created by Laren Sakota on 4/23/20.
//  Copyright © 2020 Laren Sakota. All rights reserved.
//

import Foundation
import UIKit

extension UIColor {
    
    // Copic color values from hex
    // Copic Black
    static let m0_ColorlessBlender = UIColor().colorFromHex("FFFFFF")
    static let m100_Black = UIColor().colorFromHex("2F2521")
    static let m110_SpecialBlack = UIColor().colorFromHex("231815")
    
    // Copic Blue
    static let b00_FrostBlue = UIColor().colorFromHex("EBF6FB")
    static let b000_PalePorcelainBlue = UIColor().colorFromHex("EBF7F7")
    static let b0000_PaleCelestine = UIColor().colorFromHex("F5FBFE")
    static let b01_MintBlue = UIColor().colorFromHex("E0F1F4")
    static let b02_RobinsEggBlue = UIColor().colorFromHex("C0E4F2")
    static let b04_TahitianBlue = UIColor().colorFromHex("80CDE7")
    static let b05_ProcessBlue = UIColor().colorFromHex("4EC1E6")
    static let b06_PeacockBlue = UIColor().colorFromHex("00A7E3")
    static let b12_LightBlue = UIColor().colorFromHex("7FCDEC")
    static let b16_LapisLazuli = UIColor().colorFromHex("0086C9")
    static let b21_BabyBlue = UIColor().colorFromHex("E6F2FB")
    static let b23_PhthaloBlue = UIColor().colorFromHex("A1C8EB")
    static let b24_Sky = UIColor().colorFromHex("99D2F2")
    static let b26_CobaltBlue = UIColor().colorFromHex("70B4E4")
    static let b28_RoyalBlue = UIColor().colorFromHex("0D64B0")
    static let b29_Ultramarine = UIColor().colorFromHex("006DBB")
    static let b32_PaleBlue = UIColor().colorFromHex("EAF4F9")
    static let b34_ManganeseBlue = UIColor().colorFromHex("8FC6EC")
    static let b37_AntwerpBlue = UIColor().colorFromHex("0068A2")
    static let b39_PrussianBlue = UIColor().colorFromHex("255CA7")
    static let b41_PowderBlue = UIColor().colorFromHex("EAF4FC")
    static let b45_SmokyBlue = UIColor().colorFromHex("82C2EB")
    static let b52_SoftGreenishBlue = UIColor().colorFromHex("BED6E3")
    static let b60_PaleBlueGray = UIColor().colorFromHex("E3E7F5")
    static let b63_LightHydrangea = UIColor().colorFromHex("B4C2E3")
    static let b66_Clematis = UIColor().colorFromHex("6C88C4")
    static let b69_StratosphericBlue = UIColor().colorFromHex("035AA9")
    static let b79_Iris = UIColor().colorFromHex("313994")
    static let b91_PaleGrayishBlue = UIColor().colorFromHex("DFE8EF")
    static let b93_LightCrockeryBlue = UIColor().colorFromHex("A2C8E0")
    static let b95_LightGrayishCobalt = UIColor().colorFromHex("7BA9CA")
    static let b97_NightBlue = UIColor().colorFromHex("3D7599")
    static let b99_Agate = UIColor().colorFromHex("004977")
    
    // Copic Blue Green
    static let bg000_PaleAqua = UIColor().colorFromHex("EDF6F2")
    static let bg0000_SnowGreen = UIColor().colorFromHex("F3F9F6")
    static let bg01_AquaBlue = UIColor().colorFromHex("D3EBFA")
    static let bg02_NewBlue = UIColor().colorFromHex("D2EBEE")
    static let bg05_HolidayBlue = UIColor().colorFromHex("91D2E6")
    static let bg07_PetroleumBlue = UIColor().colorFromHex("11B3D1")
    static let bg09_BlueGreen = UIColor().colorFromHex("00ACCB")
    static let bg10_CoolShadow = UIColor().colorFromHex("E6F4F3")
    static let bg11_MoonWhite = UIColor().colorFromHex("D9EEF4")
    static let bg13_MintGreen = UIColor().colorFromHex("CFEAED")
    static let bg15_Aqua = UIColor().colorFromHex("AEDBD5")
    static let bg18_TealBlue = UIColor().colorFromHex("42B9AC")
    static let bg23_CoralSea = UIColor().colorFromHex("C9E6E0")
    static let bg32_AquaMint = UIColor().colorFromHex("C7E5DA")
    static let bg34_HorizonGreen = UIColor().colorFromHex("B0DCDA")
    static let bg45_NileBlue = UIColor().colorFromHex("BCE2E4")
    static let bg49_DuckBlue = UIColor().colorFromHex("00AEB6")
    static let bg53_IceMint = UIColor().colorFromHex("B8D5D7")
    static let bg57_Jasper = UIColor().colorFromHex("6BBEBE")
    static let bg70_OceanMist = UIColor().colorFromHex("E4EFF1")
    static let bg72_IceOcean = UIColor().colorFromHex("7BBABE")
    static let bg75_AbyssGreen = UIColor().colorFromHex("538F8D")
    static let bg78_Bronze = UIColor().colorFromHex("3D6D64")
    static let bg90_GraySky = UIColor().colorFromHex("EFF3ED")
    static let bg93_GreenGray = UIColor().colorFromHex("C9CEC3")
    static let bg96_Bush = UIColor().colorFromHex("90AD99")
    static let bg99_FlagstoneBlue = UIColor().colorFromHex("7CA58F")
    
    // Copic Blue Violet
    static let bv00_MauveShadow = UIColor().colorFromHex("E8E3F1")
    static let bv000_IridescentMauve = UIColor().colorFromHex("EDE6F2")
    static let bv0000_PaleThistle = UIColor().colorFromHex("F0ECF6")
    static let bv01_Viola = UIColor().colorFromHex("D0D1E9")
    static let bv02_Prune = UIColor().colorFromHex("B7BFE0")
    static let bv04_BlueBerry = UIColor().colorFromHex("869ACE")
    static let bv08_BlueViolet = UIColor().colorFromHex("A67EB7")
    static let bv11_SoftViolet = UIColor().colorFromHex("DDD9EC")
    static let bv13_HydrangeaBlue = UIColor().colorFromHex("8D93C8")
    static let bv17_DeepReddishBlue = UIColor().colorFromHex("7184BC")
    static let bv20_DullLavender = UIColor().colorFromHex("DAE2F3")
    static let bv23_GrayishLavender = UIColor().colorFromHex("C0CBE3")
    static let bv25_GrayishViolet = UIColor().colorFromHex("8585AA")
    static let bv29_Slate = UIColor().colorFromHex("2A3F52")
    static let bv31_PaleLavender = UIColor().colorFromHex("E5E8F5")
    static let bv34_Bluebell = UIColor().colorFromHex("AFB5C8")
    
    // Copic Cool Gray
    static let c0_CoolGray = UIColor().colorFromHex("EDF2F5")
    static let c00_CoolGray = UIColor().colorFromHex("F0F4F7")
    static let c1_CoolGray = UIColor().colorFromHex("E6EBEE")
    static let c2_CoolGray = UIColor().colorFromHex("D9E1E5")
    static let c3_CoolGray = UIColor().colorFromHex("CED6DB")
    static let c4_CoolGray = UIColor().colorFromHex("B7C1C8")
    static let c5_CoolGray = UIColor().colorFromHex("A3ADB4")
    static let c6_CoolGray = UIColor().colorFromHex("8B979E")
    static let c7_CoolGray = UIColor().colorFromHex("6D767C")
    static let c8_CoolGray = UIColor().colorFromHex("585F64")
    static let c9_CoolGray = UIColor().colorFromHex("3E4449")
    static let c10_CoolGray = UIColor().colorFromHex("222327")
    
    // Copic Earth
    static let e00_SkinWhite = UIColor().colorFromHex("FEF7EF")
    static let e000_PaleFruitPink = UIColor().colorFromHex("FFF8F2")
    static let e0000_FloralWhite = UIColor().colorFromHex("FFFCF7")
    static let e01_PinkFlamingo = UIColor().colorFromHex("FEF3E9")
    static let e02_FruitPink = UIColor().colorFromHex("FEF1E6")
    static let e04_NaturalLipstick = UIColor().colorFromHex("EAC8CE")
    static let e07_LightMahogany = UIColor().colorFromHex("D3896B")
    static let e08_Brown = UIColor().colorFromHex("CE684D")
    static let e09_BurntSienna = UIColor().colorFromHex("DA6744")
    static let e11_BarleyBeige = UIColor().colorFromHex("FEEFDE")
    static let e13_LightSuntan = UIColor().colorFromHex("EDCFB8")
    static let e15_DarkSuntan = UIColor().colorFromHex("F8C28C")
    static let e17_ReddishBrass = UIColor().colorFromHex("BA5C4B")
    static let e18_Copper = UIColor().colorFromHex("8B4E43")
    static let e19_Redwood = UIColor().colorFromHex("C44D2B")
    static let e21_BabySkinPink = UIColor().colorFromHex("FDE8D0")
    static let e23_Hazelnut = UIColor().colorFromHex("EED1B6")
    static let e25_CaribeCocoa = UIColor().colorFromHex("DBB089")
    static let e27_Africano = UIColor().colorFromHex("A27B5F")
    static let e29_BurntUmber = UIColor().colorFromHex("843F2D")
    static let e30_Bisque = UIColor().colorFromHex("FBF6EA")
    static let e31_BrickBeige = UIColor().colorFromHex("F7ECD7")
    static let e33_Sand = UIColor().colorFromHex("F5DBB8")
    static let e34_Orientale = UIColor().colorFromHex("F3D5AD")
    static let e35_Chamois = UIColor().colorFromHex("ECD0AD")
    static let e37_Sepia = UIColor().colorFromHex("D39D57")
    static let e39_Leather = UIColor().colorFromHex("C9732F")
    static let e40_BrickWhite = UIColor().colorFromHex("F8F1E6")
    static let e41_PearlWhite = UIColor().colorFromHex("FEF4E8")
    static let e42_SandWhite = UIColor().colorFromHex("F7F1E2")
    static let e43_DullIvory = UIColor().colorFromHex("F0E6C9")
    static let e44_Clay = UIColor().colorFromHex("D2C7B3")
    static let e47_DarkBrown = UIColor().colorFromHex("917860")
    static let e49_DarkBark = UIColor().colorFromHex("6C5037")
    static let e50_EggShell = UIColor().colorFromHex("F6F0F3")
    static let e51_MilkyWhite = UIColor().colorFromHex("FEF0DD")
    static let e53_RawSilk = UIColor().colorFromHex("F8EDCB")
    static let e55_LightCamel = UIColor().colorFromHex("F5E6C1")
    static let e57_LightWalnut = UIColor().colorFromHex("BC925B")
    static let e59_Walnut = UIColor().colorFromHex("A4866A")
    static let e70_AshRose = UIColor().colorFromHex("F4EFEC")
    static let e71_Champagne = UIColor().colorFromHex("E9E0DA")
    static let e74_CocoaBrown = UIColor().colorFromHex("AE9183")
    static let e77_Maroon = UIColor().colorFromHex("886449")
    static let e79_Cashew = UIColor().colorFromHex("4B2C1F")
    static let e81_Ivory = UIColor().colorFromHex("F2EBC6")
    static let e84_Khaki = UIColor().colorFromHex("B7A880")
    static let e87_Fig = UIColor().colorFromHex("78664B")
    static let e89_Pecan = UIColor().colorFromHex("614B34")
    static let e93_TeaRose = UIColor().colorFromHex("FBD9BF")
    static let e95_FleshPink = UIColor().colorFromHex("F9C37B")
    static let e97_DeepOrange = UIColor().colorFromHex("ECA153")
    static let e99_BakedClay = UIColor().colorFromHex("B65C22")
    
    // Copic Fluorescent
    static let fb2_FluorescentDullBlue = UIColor().colorFromHex("0089CE")
    static let fbg2_FluorescentDullBlueGreen = UIColor().colorFromHex("71C9E8")
    static let frv1_FluorescentPink = UIColor().colorFromHex("F3A9C9")
    static let fv2_FluorescentDullViolet = UIColor().colorFromHex("8471B2")
    static let fy1_FluorescentYellowOrange = UIColor().colorFromHex("FFF796")
    static let fyg1_FluorescentYellow = UIColor().colorFromHex("D7E3A2")
    static let fyg2_FluorescentDullYellowGreen = UIColor().colorFromHex("A3CB23")
    static let fyr1_FluorescentOrange = UIColor().colorFromHex("FBD39C")
    
    // Copic Green
    static let g00_JadeGreen = UIColor().colorFromHex("EBF6F7")
    static let g000_PaleGreen = UIColor().colorFromHex("EFF7F0")
    static let g0000_CrystalOpal = UIColor().colorFromHex("F6FAF6")
    static let g02_SpectrumGreen = UIColor().colorFromHex("D8EBD8")
    static let g03_MeadowGreen = UIColor().colorFromHex("BEDC98")
    static let g05_EmeraldGreen = UIColor().colorFromHex("6BBC6E")
    static let g07_NileGreen = UIColor().colorFromHex("7FC26B")
    static let g09_VeroneseGreen = UIColor().colorFromHex("7DC058")
    static let g12_SeaGreen = UIColor().colorFromHex("DBEBC8")
    static let g14_AppleGreen = UIColor().colorFromHex("9FCF88")
    static let g16_Malachite = UIColor().colorFromHex("62BD92")
    static let g17_ForestGreen = UIColor().colorFromHex("00AA74")
    static let g19_BrightParrotGreen = UIColor().colorFromHex("2CB280")
    static let g20_WaxWhite = UIColor().colorFromHex("F2F7E0")
    static let g21_LimeGreen = UIColor().colorFromHex("CFE7D1")
    static let g24_Willow = UIColor().colorFromHex("CBE3B5")
    static let g28_OceanGreen = UIColor().colorFromHex("00925C")
    static let g29_PineTreeGreen = UIColor().colorFromHex("207F5C")
    static let g40_DimGreen = UIColor().colorFromHex("ECF4E3")
    static let g43_Pistachio = UIColor().colorFromHex("DEEAA8")
    static let g46_Mistletoe = UIColor().colorFromHex("5FA271")
    static let g82_SpringDimGreen = UIColor().colorFromHex("D9E3C2")
    static let g85_Verdigris = UIColor().colorFromHex("ACCCB0")
    static let g94_GrayishOlive = UIColor().colorFromHex("A0AD83")
    static let g99_Olive = UIColor().colorFromHex("6B8631")
    
    // Copic Neutral Gray
    static let n0_NeutralGray = UIColor().colorFromHex("F2F2F3")
    static let n1_NeutralGray = UIColor().colorFromHex("EBEBEC")
    static let n2_NeutralGray = UIColor().colorFromHex("E4E4E5")
    static let n3_NeutralGray = UIColor().colorFromHex("DCDDDD")
    static let n4_NeutralGray = UIColor().colorFromHex("C9CACA")
    static let n5_NeutralGray = UIColor().colorFromHex("B5B5B6")
    static let n6_NeutralGray = UIColor().colorFromHex("9FA0A0")
    static let n7_NeutralGray = UIColor().colorFromHex("7D7D7D")
    static let n8_NeutralGray = UIColor().colorFromHex("666464")
    static let n9_NeutralGray = UIColor().colorFromHex("4C4948")
    static let n10_NeutralGray = UIColor().colorFromHex("2F2725")
    
    // Copic Red
    static let r00_PinkishWhite = UIColor().colorFromHex("FEF5F0")
    static let r000_CherryWhite = UIColor().colorFromHex("FEF7F2")
    static let r0000_PinkBeryl = UIColor().colorFromHex("FEF7F2")
    static let r01_PinkishVanilla = UIColor().colorFromHex("FCE8E1")
    static let r02_Flesh = UIColor().colorFromHex("FBDACD")
    static let r05_SalmonRed = UIColor().colorFromHex("F19478")
    static let r08_Vermilion = UIColor().colorFromHex("EB6148")
    static let r11_PaleCherryPink = UIColor().colorFromHex("FCE8DC")
    static let r12_LightTeaRose = UIColor().colorFromHex("FBDAC8")
    static let r14_LightRouge = UIColor().colorFromHex("F2A093")
    static let r17_LipstickOrange = UIColor().colorFromHex("EF8463")
    static let r20_Blush = UIColor().colorFromHex("FBDFD8")
    static let r21_Sardonyx = UIColor().colorFromHex("F8C8BD")
    static let r22_LightPrawn = UIColor().colorFromHex("F7BEB7")
    static let r24_Prawn = UIColor().colorFromHex("EC7274")
    static let r27_CadmiumRed = UIColor().colorFromHex("E94957")
    static let r29_LipstickRed = UIColor().colorFromHex("E6003E")
    static let r30_PaleYellowishPink = UIColor().colorFromHex("FDEAE6")
    static let r32_Peach = UIColor().colorFromHex("F8C8C0")
    static let r35_Coral = UIColor().colorFromHex("EC6D7F")
    static let r37_Carmine = UIColor().colorFromHex("E56B70")
    static let r39_Garnet = UIColor().colorFromHex("CD4479")
    static let r43_Bougainvillea = UIColor().colorFromHex("EA848C")
    static let r46_StrongRed = UIColor().colorFromHex("DD4660")
    static let r56_Currant = UIColor().colorFromHex("D8829B")
    static let r59_Cardinal = UIColor().colorFromHex("BE5072")
    static let r81_RosePink = UIColor().colorFromHex("F4D2DE")
    static let r83_RoseMist = UIColor().colorFromHex("EFA1BC")
    static let r85_RoseRed = UIColor().colorFromHex("D66793")
    static let r89_DarkRed = UIColor().colorFromHex("862740")
    
    // Copic Red Violet
    static let rv00_WaterLily = UIColor().colorFromHex("F4E1EE")
    static let rv000_PalePurple = UIColor().colorFromHex("F7E9F2")
    static let rv0000_EveningPrimrose = UIColor().colorFromHex("F6EFF6")
    static let rv02_SugaredAlmondPink = UIColor().colorFromHex("FADCE9")
    static let rv04_ShockPink = UIColor().colorFromHex("F3A9C3")
    static let rv06_Cerise = UIColor().colorFromHex("EE86AE")
    static let rv09_Fuchsia = UIColor().colorFromHex("DF6DA6")
    static let rv10_PalePink = UIColor().colorFromHex("FDF0F6")
    static let rv11_Pink = UIColor().colorFromHex("FBDEE3")
    static let rv13_TenderPink = UIColor().colorFromHex("F8D1DE")
    static let rv14_BegoniaPink = UIColor().colorFromHex("F097B8")
    static let rv17_DeepMagenta = UIColor().colorFromHex("DD7DAF")
    static let rv19_RedViolet = UIColor().colorFromHex("D464A1")
    static let rv21_LightPink = UIColor().colorFromHex("FDEEEE")
    static let rv23_PurePink = UIColor().colorFromHex("F7C2CE")
    static let rv25_DogRoseFlower = UIColor().colorFromHex("F097BE")
    static let rv29_Crimson = UIColor().colorFromHex("E73D78")
    static let rv32_ShadowPink = UIColor().colorFromHex("FADBD6")
    static let rv34_DarkPink = UIColor().colorFromHex("F5B6B3")
    static let rv42_SalmonPink = UIColor().colorFromHex("F7C2BB")
    static let rv52_CottonCandy = UIColor().colorFromHex("F8D1E2")
    static let rv55_Hollyhock = UIColor().colorFromHex("EBAECD")
    static let rv63_Begonia = UIColor().colorFromHex("D5A4B0")
    static let rv66_Raspberry = UIColor().colorFromHex("BD6982")
    static let rv69_Peony = UIColor().colorFromHex("92556D")
    static let rv91_GrayishCherry = UIColor().colorFromHex("EDDDE9")
    static let rv93_SmokeyPurple = UIColor().colorFromHex("EABED1")
    static let rv95_BabyBlossoms = UIColor().colorFromHex("BF8AA7")
    static let rv99_ArgylePurple = UIColor().colorFromHex("60485A")
    
    // Copic Toner Gray
    static let t0_TonerGray = UIColor().colorFromHex("F2F2F3")
    static let t1_TonerGray = UIColor().colorFromHex("F1F1F0")
    static let t2_TonerGray = UIColor().colorFromHex("E9EAE8")
    static let t3_TonerGray = UIColor().colorFromHex("DDDCD8")
    static let t4_TonerGray = UIColor().colorFromHex("C9C9C6")
    static let t5_TonerGray = UIColor().colorFromHex("B5B4B0")
    static let t6_TonerGray = UIColor().colorFromHex("9F9F9B")
    static let t7_TonerGray = UIColor().colorFromHex("7D7C78")
    static let t8_TonerGray = UIColor().colorFromHex("666460")
    static let t9_TonerGray = UIColor().colorFromHex("4C4845")
    static let t10_TonerGray = UIColor().colorFromHex("2F2722")
    
    // Copic Violet
    static let v000_PaleHeath = UIColor().colorFromHex("EFEBF5")
    static let v0000_RoseQuartz = UIColor().colorFromHex("F4F2F8")
    static let v01_Heath = UIColor().colorFromHex("E9C9DF")
    static let v04_Lilac = UIColor().colorFromHex("E8B2D0")
    static let v05_Marigold = UIColor().colorFromHex("E6ADCD")
    static let v06_Lavender = UIColor().colorFromHex("D49BC4")
    static let v09_Violet = UIColor().colorFromHex("894A99")
    static let v12_PaleLilac = UIColor().colorFromHex("F1DDEC")
    static let v15_Mallow = UIColor().colorFromHex("DAAED0")
    static let v17_Amethyst = UIColor().colorFromHex("AA96C6")
    static let v20_Wisteria = UIColor().colorFromHex("E6E3F0")
    static let v22_AshLavender = UIColor().colorFromHex("C1BBD7")
    static let v25_PaleBlackberry = UIColor().colorFromHex("897FAF")
    static let v28_Eggplant = UIColor().colorFromHex("776D94")
    static let v91_PaleGrape = UIColor().colorFromHex("ECCDD8")
    static let v93_EarlyGrape = UIColor().colorFromHex("E9C9E0")
    static let v95_LightGrape = UIColor().colorFromHex("BC7CA6")
    static let v99_Aubergine = UIColor().colorFromHex("463A4E")
    
    // Copic Warm Gray
    static let w0_WarmGray = UIColor().colorFromHex("F8F7F1")
    static let w00_WarmGray = UIColor().colorFromHex("F8F7F2")
    static let w1_WarmGray = UIColor().colorFromHex("EFEFE9")
    static let w2_WarmGray = UIColor().colorFromHex("EFEFEB")
    static let w3_WarmGray = UIColor().colorFromHex("DDDCD6")
    static let w4_WarmGray = UIColor().colorFromHex("C9C9C2")
    static let w5_WarmGray = UIColor().colorFromHex("B5B5AF")
    static let w6_WarmGray = UIColor().colorFromHex("9F9F99")
    static let w7_WarmGray = UIColor().colorFromHex("7D7C77")
    static let w8_WarmGray = UIColor().colorFromHex("66645F")
    static let w9_WarmGray = UIColor().colorFromHex("4C4944")
    static let w10_WarmGray = UIColor().colorFromHex("2F2721")
    
    // Copic Yellow
    static let y00_BariumYellow = UIColor().colorFromHex("FFFDE5")
    static let y000_PaleLemon = UIColor().colorFromHex("FFFEEE")
    static let y0000_YellowFluorite = UIColor().colorFromHex("FFFEF7")
    static let y02_CanaryYellow = UIColor().colorFromHex("FBF496")
    static let y04_Acacia = UIColor().colorFromHex("F1E844")
    static let y06_Yellow = UIColor().colorFromHex("FFF462")
    static let y08_AcidYellow = UIColor().colorFromHex("FFF100")
    static let y11_PaleYellow = UIColor().colorFromHex("FFFCD1")
    static let y13_LemonYellow = UIColor().colorFromHex("FEF8B0")
    static let y15_CadmiumYellow = UIColor().colorFromHex("FFEB63")
    static let y17_GoldenYellow = UIColor().colorFromHex("FFE746")
    static let y18_LightningYellow = UIColor().colorFromHex("FFEF47")
    static let y19_NapoliYellow = UIColor().colorFromHex("FFEB27")
    static let y21_ButtercupYellow = UIColor().colorFromHex("FFF2C6")
    static let y23_YellowishBeige = UIColor().colorFromHex("FDEABA")
    static let y26_Mustard = UIColor().colorFromHex("F5E35F")
    static let y28_LionetGold = UIColor().colorFromHex("CEAF60")
    static let y32_Cashmere = UIColor().colorFromHex("FAE5C7")
    static let y35_Maize = UIColor().colorFromHex("FEDD73")
    static let y38_Honey = UIColor().colorFromHex("FDD86C")
    
    // Copic Yellow Green
    static let yg00_MimosaYellow = UIColor().colorFromHex("EBEB9E")
    static let yg0000_LilyWhite = UIColor().colorFromHex("F6F9E4")
    static let yg01_GreenBice = UIColor().colorFromHex("EDF2C5")
    static let yg03_YellowGreen = UIColor().colorFromHex("E6EDAB")
    static let yg05_Salad = UIColor().colorFromHex("DEE88E")
    static let yg06_YellowishGreen = UIColor().colorFromHex("CDE18D")
    static let yg07_AcidGreen = UIColor().colorFromHex("AACE36")
    static let yg09_LettuceGreen = UIColor().colorFromHex("83C257")
    static let yg11_Mignonette = UIColor().colorFromHex("EAF2D3")
    static let yg13_Chartreuse = UIColor().colorFromHex("DAE79D")
    static let yg17_GrassGreen = UIColor().colorFromHex("71BB48")
    static let yg21_Anise = UIColor().colorFromHex("FBF8C2")
    static let yg23_NewLeaf = UIColor().colorFromHex("ECED8D")
    static let yg25_CeladonGreen = UIColor().colorFromHex("D6E272")
    static let yg41_PaleCobaltGreen = UIColor().colorFromHex("DFEED8")
    static let yg45_CobaltGreen = UIColor().colorFromHex("BFDFB8")
    static let yg61_PaleMoss = UIColor().colorFromHex("DEECDB")
    static let yg63_PeaGreen = UIColor().colorFromHex("ADD1A4")
    static let yg67_Moss = UIColor().colorFromHex("8AC287")
    static let yg91_Putty = UIColor().colorFromHex("E1DEB3")
    static let yg93_GrayishYellow = UIColor().colorFromHex("D9D99D")
    static let yg95_PaleOlive = UIColor().colorFromHex("D6D057")
    static let yg97_SpanishOlive = UIColor().colorFromHex("A09900")
    static let yg99_MarineGreen = UIColor().colorFromHex("596F00")
    
    // Copic Yellow Red
    static let yr00_PowderPink = UIColor().colorFromHex("FBDDC4")
    static let yr000_Silk = UIColor().colorFromHex("FEF0E1")
    static let yr0000_PaleChiffon = UIColor().colorFromHex("FFF6EB")
    static let yr01_PeachPuff = UIColor().colorFromHex("FCE1C8")
    static let yr02_LightOrange = UIColor().colorFromHex("FCE3CD")
    static let yr04_ChromeOrange = UIColor().colorFromHex("FBCA5E")
    static let yr07_CadmiumOrange = UIColor().colorFromHex("ED6D2B")
    static let yr09_ChineseOrange = UIColor().colorFromHex("EA5006")
    static let yr12_Loquat = UIColor().colorFromHex("FEE7A9")
    static let yr14_Caramel = UIColor().colorFromHex("FCCF3E")
    static let yr15_PumpkinYellow = UIColor().colorFromHex("F5A340")
    static let yr16_Apricot = UIColor().colorFromHex("FABE00")
    static let yr18_Sanguine = UIColor().colorFromHex("EC682C")
    static let yr20_YellowishShade = UIColor().colorFromHex("FDE8C6")
    static let yr21_Cream = UIColor().colorFromHex("F7E4B6")
    static let yr23_YellowOchre = UIColor().colorFromHex("F0D98F")
    static let yr24_PaleSepia = UIColor().colorFromHex("F4D95B")
    static let yr27_TuscanOrange = UIColor().colorFromHex("D56227")
    static let yr30_MacadamiaNut = UIColor().colorFromHex("FFF6E2")
    static let yr31_LightReddishYellow = UIColor().colorFromHex("FEE4AB")
    static let yr61_YellowishSkinPink = UIColor().colorFromHex("FCE1CA")
    static let yr65_Atoll = UIColor().colorFromHex("F7B455")
    static let yr68_Orange = UIColor().colorFromHex("ED6C00")
    static let yr82_MellowPeach = UIColor().colorFromHex("FACD8D")
    
    
    func colorFromHex(_ hex: String) -> UIColor {
        var hexString = hex.trimmingCharacters(in: .whitespacesAndNewlines).uppercased()
        
        if hexString.hasPrefix("#") {
            hexString.remove(at: hexString.startIndex)
        }
        
        if hexString.count != 6 {
            return UIColor.black
        }
        
        var rgb: UInt64 = 0
        Scanner(string: hexString).scanHexInt64(&rgb)
        
        return UIColor.init(red: CGFloat((rgb & 0xFF0000) >> 16) / 255.0,
                            green: CGFloat((rgb & 0x00FF00) >> 8) / 255.0,
                            blue: CGFloat(rgb & 0x0000FF) / 255.0,
                            alpha: 1.0)
    }
}
